/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/ShoeModelDraco.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Sole.geometry} material={materials.Sole} position={[0.82, 1, 0]} scale={[0.62, 1, 0.63]} />
      <mesh geometry={nodes.Tongue.geometry} material={materials.Tongue} position={[-0.07, 1.09, 0]} scale={[0.62, 1, 0.63]} />
      <mesh geometry={nodes.ToeCap.geometry} material={materials.ToeCap} position={[-1.01, 0.73, 0]} scale={[0.69, 1.2, 0.66]} />
      <mesh geometry={nodes.Interior.geometry} material={materials.Interior} position={[0.89, 1.62, 0]} scale={[0.39, 0.63, 0.4]} />
      <mesh geometry={nodes.Base.geometry} material={materials.Base} position={[0.82, 0.95, 0]} scale={[0.62, 1, 0.63]} />
      <mesh geometry={nodes.Lace_01.geometry} material={materials.Lace_01} position={[0.27, 1.38, 0]} rotation={[0, Math.PI / 2, 0]} scale={[0.25, 0.22, 0.22]} />
      <mesh geometry={nodes.Lace_02.geometry} material={materials.Lace_02} position={[0.18, 1.15, 0]} rotation={[Math.PI / 2, 1.08, -Math.PI / 2]} scale={[0.25, 0.22, 0.22]} />
      <mesh geometry={nodes.Lace_03.geometry} material={materials.Lace_03} position={[-0.02, 0.99, 0]} rotation={[Math.PI / 2, 0.48, -Math.PI / 2]} scale={[0.25, 0.22, 0.22]} />
      <mesh geometry={nodes.Lace_04.geometry} material={materials.Lace_04} position={[-0.23, 0.92, 0]} rotation={[Math.PI / 2, 0.27, -Math.PI / 2]} scale={[0.25, 0.22, 0.22]} />
      <mesh geometry={nodes.Lace_05.geometry} material={materials.Lace_05} position={[-0.46, 0.86, 0]} rotation={[Math.PI / 2, 0.31, -Math.PI / 2]} scale={[0.25, 0.22, 0.22]} />
    </group>
  )
}

useGLTF.preload('/ShoeModelDraco.glb')
